#Reset
set_property PACKAGE_PIN U18 [get_ports RESET]
    set_property IOSTANDARD LVCMOS33 [get_ports RESET]
    
#CLK
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
    
#Mapping the data and mouse clocks to their correct pins
set_property PACKAGE_PIN C17 [get_ports {CLK_MOUSE}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CLK_MOUSE}]
    set_property PULLUP true [get_ports {CLK_MOUSE}]
set_property PACKAGE_PIN B17 [get_ports {DATA_MOUSE}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DATA_MOUSE}]
    set_property PULLUP true [get_ports {DATA_MOUSE}]

#Mapping the output from the 7 segment decoder to the correct pins on the 7 segment display
set_property PACKAGE_PIN U2 [get_ports {SEG_SELECT_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[0]}]
set_property PACKAGE_PIN U4 [get_ports {SEG_SELECT_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[1]}]
set_property PACKAGE_PIN V4 [get_ports {SEG_SELECT_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[2]}]
set_property PACKAGE_PIN W4 [get_ports {SEG_SELECT_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[3]}]
   
set_property PACKAGE_PIN W7 [get_ports {DISP_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[0]}]
set_property PACKAGE_PIN W6 [get_ports {DISP_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[1]}]
set_property PACKAGE_PIN U8 [get_ports {DISP_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[2]}]
set_property PACKAGE_PIN V8 [get_ports {DISP_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[3]}]
set_property PACKAGE_PIN U5 [get_ports {DISP_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[4]}]
set_property PACKAGE_PIN V5 [get_ports {DISP_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[5]}]
set_property PACKAGE_PIN U7 [get_ports {DISP_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[6]}]
set_property PACKAGE_PIN V7 [get_ports {DISP_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DISP_OUT[7]}]
    
set_property PACKAGE_PIN V17 [get_ports {SLIDE_SWITCHES[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[0]}]
set_property PACKAGE_PIN V16 [get_ports {SLIDE_SWITCHES[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[1]}]
set_property PACKAGE_PIN W16 [get_ports {SLIDE_SWITCHES[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[2]}]
set_property PACKAGE_PIN W17 [get_ports {SLIDE_SWITCHES[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[3]}]
set_property PACKAGE_PIN W15 [get_ports {SLIDE_SWITCHES[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[4]}]
set_property PACKAGE_PIN V15 [get_ports {SLIDE_SWITCHES[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[5]}]
set_property PACKAGE_PIN W14 [get_ports {SLIDE_SWITCHES[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[6]}]
set_property PACKAGE_PIN W13 [get_ports {SLIDE_SWITCHES[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[7]}]
set_property PACKAGE_PIN V2 [get_ports {SLIDE_SWITCHES[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[8]}]
set_property PACKAGE_PIN T3 [get_ports {SLIDE_SWITCHES[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[9]}]
set_property PACKAGE_PIN T2 [get_ports {SLIDE_SWITCHES[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[10]}]
set_property PACKAGE_PIN R3 [get_ports {SLIDE_SWITCHES[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[11]}]
set_property PACKAGE_PIN W2 [get_ports {SLIDE_SWITCHES[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[12]}]
set_property PACKAGE_PIN U1 [get_ports {SLIDE_SWITCHES[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[13]}]
set_property PACKAGE_PIN T1 [get_ports {SLIDE_SWITCHES[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[14]}]
set_property PACKAGE_PIN R2 [get_ports {SLIDE_SWITCHES[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCHES[15]}]    
    
set_property PACKAGE_PIN U17 [get_ports {LEDS[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDS[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDS[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDS[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDS[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDS[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDS[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDS[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[7]}]
set_property PACKAGE_PIN V13 [get_ports {LEDS[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[8]}]
set_property PACKAGE_PIN V3 [get_ports {LEDS[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[9]}]
set_property PACKAGE_PIN W3 [get_ports {LEDS[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[10]}]
set_property PACKAGE_PIN U3 [get_ports {LEDS[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[11]}]
set_property PACKAGE_PIN P3 [get_ports {LEDS[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[12]}]
set_property PACKAGE_PIN N3 [get_ports {LEDS[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[13]}]
set_property PACKAGE_PIN P1 [get_ports {LEDS[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[14]}]
set_property PACKAGE_PIN L1 [get_ports {LEDS[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDS[15]}]

#VGA Colours
set_property PACKAGE_PIN G19 [get_ports {COLOUR_OUT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[0]}]
    
set_property PACKAGE_PIN H19 [get_ports {COLOUR_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[1]}]
    
set_property PACKAGE_PIN J19 [get_ports {COLOUR_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[2]}]
    
set_property PACKAGE_PIN N19 [get_ports {COLOUR_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[3]}]
set_property PACKAGE_PIN J17 [get_ports {COLOUR_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[4]}]
    
set_property PACKAGE_PIN H17 [get_ports {COLOUR_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[5]}]
    
set_property PACKAGE_PIN G17 [get_ports {COLOUR_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[6]}]
    
set_property PACKAGE_PIN D17 [get_ports {COLOUR_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[7]}]

#Synchronisation signals
set_property PACKAGE_PIN P19 [get_ports HS]
    set_property IOSTANDARD LVCMOS33 [get_ports HS]
    
set_property PACKAGE_PIN R19 [get_ports VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VS]
    
#IR LED
set_property PACKAGE_PIN G2 [get_ports IR_LED]
    set_property IOSTANDARD LVCMOS33 [get_ports IR_LED]
