# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet {{C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.runs/ila_0_synth_1/ila_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.runs/ila_0_synth_1/ila_0.dcp}}]
read_mem {
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/ROM_COMPLETE.mem}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/RAM_COMPLETE.mem}
}
read_verilog -library xil_defaultlib {
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/MouseTransmitter.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/MouseReceiver.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/MouseMasterSM.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Generic_counter.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/seg7Decoder.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Multiplexer_4way.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/VGA_Sig_Gen.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Frame_Buffer.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/TenHz_cnt.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/IRTransmitterSM.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/MouseTransceiver.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/ALU.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/Disp_Seg7.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Slideswitches_BUS.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/VGA_Wrapper.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/new/IRTransmitter.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Timer.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/ROM.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/RAM.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Processor.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/Mouse_BUS.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/LEDS_BUS.v}
  {C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/sources_1/imports/new/TopLevel.v}
}
read_xdc {{C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/constrs_1/new/Final_XDC.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Thomas Deppe/DSL_Projects/Final_Processor/Final_Processor.srcs/constrs_1/new/Final_XDC.xdc}}]

synth_design -top TopLevel -part xc7a35tcpg236-1
write_checkpoint -noxdef TopLevel.dcp
catch { report_utilization -file TopLevel_utilization_synth.rpt -pb TopLevel_utilization_synth.pb }
